ctrlpvim/ctrlp.vim

- autoload/ctrlp/bookmarkdir.vim
- autoload/ctrlp/mrufiles.vim
- doc/ctrlp.txt
Commit https://github.com/Konfekt/ctrlp.vim/commit/f6cb0f07eb41ea47eb83efc2e75a123abbad6d10 resolves that  `:CtrlPBookmarkDir!` adds the `cwd` twice: With and without a trailing slash.
Commit https://github.com/Konfekt/ctrlp.vim/commit/553f25050c52f730ba5cd3326b01a7a96b93dd50 adds an option `g:ctrlp_mruf_tilde_homedir` to save MRU and `CtrlPBookmarkDir!` added paths (that can be used to build a directory MRU) as path's relative to the home dir. That is, with `g:ctrlp_mruf_tilde_homedir=1` (but = 0 by default) `/home/username/file` will be saved as `~/file`.
This way,
* the MRU contains less unnecessary clutter, and
* the MRU stays valid if the full path of $HOME changes (for example on Windows, under cygwin and under other accounts)
> Remove typo to uniformize dir path & Make $HOME in MRU relative

- autoload/ctrlp.vim
- autoload/ctrlp/bookmarkdir.vim
- autoload/ctrlp/mrufiles.vim
- doc/ctrlp.txt
For example, when searching for .txt the MRU is crammed by recent accesses to the VIM doc by K. With this addtitional option g:ctrlp_mruf_exclude_nomod, these files, as well as all other nonmodifiable buffers are no longer added to the MRU list.
I also cleaned up the autocmd events for the MRU list. Please check that it suits you. Regardless, the BufWinEnter autocmd is crucial to check at the right time if the buffer is nonmodifiable.
> Nomod (follow up to https://github.com/ctrlpvim/ctrlp.vim/pull/43)

- autoload/ctrlp.vim
Made the default string of '> ' an option instead, since printing > in the CtrlP-window breaks syntax highlighting for some things in CtrlP-funky.
> added option g:ctrlp_line_prefix. Default: '> '

- autoload/ctrlp.vim
It would be nice to treat terminals in neovim as buffers accessible through CtrlP.
> Add support for terminal buffers on neovim

- autoload/ctrlp/tag.vim
Starting with commit 83397bd0, when possible Ctrlp tries to autoselect
a tag from from the `tselect` menu.
This has a significant flaw though, as it does not select the correct tag
when there are multiple tags with the same name in the same file, instead
preferring to always use the last tag from that file.
By matching not just on filename of the selected tag, but also on the
tagaddress (generally a regex or linenumber), we ensure that the correct
tag is always selected from the tselect prompt.
> Fix auto selection of tag from tselect menu for tags in the same file.

- autoload/ctrlp.vim
This fixes #106. Tested with NVIM 0.0.0-alpha+201507232235 (compiled Jul 25 2015 23:03:14)
> Fix buffer mode to handle neovim terminal buffer properly (#106)

- autoload/ctrlp/mrufiles.vim
I have already completely this in a somewhat hacky way, but this would allow for a cleaner way to customize the list items format.
Reference to my use case: ryanoasis/vim-devicons/issues/56
```vim
" scope: local
" Either initialize for: kien/ctrlp.vim OR up to date fork: ctrlpvim/ctrlp.vim
" mostly a hack/overwrite to add icons to the official inactive ctrlP repo
" only overwriting the necessary functions to make it work
" unless we detect the newer active ctrlp fork
function! s:initializeCtrlP()
if exists("g:loaded_ctrlp") && g:webdevicons_enable_ctrlp
let g:ctrlp_open_func = {
\ 'files': 'webdevicons#ctrlPOpenFunc',
\ 'buffers': 'webdevicons#ctrlPOpenFunc',
\ 'mru files': 'webdevicons#ctrlPOpenFunc'
\ }
if exists("g:ctrlp_mruf_map_string")
" logic for ctrlpvim/ctrlp.vim:
let …
```
> Allow easier customizing of list format

- autoload/ctrlp.vim
Trying neovim, one thing I noticed was that CtrlPMixed was a lot slower. After investigation this seemed to be caused by the fact I use an external command for the file list. Using `split(system())` seems to be quite slow on neovim, while `systemlist` does work well. However, older versions of vim have an issue using `systemlist`, which is fixed in 7.4.597, hence the check.
> Improve perfomance using external command in neovim

- autoload/ctrlp.vim
Tmux now has its own terminfo: tmux and tmux-256color. The arrow key mapping needs to be done on these terminfo too.
> Fix arrow key for tmux

- autoload/ctrlp.vim
This is to better follow root markers' order.
> Change how project roots are found.

- doc/ctrlp.cnx
- doc/ctrlp.txt
- readme.md
`cd %s && git ls-files` works better in combination with a custom
`ctrlp_root_markers`.
> Docs: do not recommend `--git-dir=%s/.git`

- autoload/ctrlp.vim
The problem is the cursor position is reset to the top forcibly
if nolim is set to 1 when you tried to  current line.
> Fix to be able to change the active line

- autoload/ctrlp/buffertag.vim
*jsctags* would not work on Windows for me. The `shellescape` function surrounds the `jsctags` cmd with `"`. I observed that this was the error cause. Removing the `"` stop the issue and *jsctags* works as expected. I admit I don't really understand the full extent of this fix. It may not be the best solution. 
I will test the fix on OSX later today and comment back.
> Fix jsctags not working on Windows

- autoload/ctrlp/mrufiles.vim
- doc/ctrlp.cnx
- doc/ctrlp.txt
For example after comitting from vim-fugitive, there is a temp file added to the MRU. This option prevents this.
Also cleaned up the check if the buffer name should go to the MRU as a whole.
> cleanup mru record function

- autoload/ctrlp.vim
In user command, `%s` is replaced with a target directory path. On
Windows, this path is always separated by backslashes. If a user
configures `shell` option to `sh` (or something similar), a shell cannot
understand a target directory path and probably cannot list files.
This commit checks the `shell` option on Windows. If this option
contains `sh`, a target directory path is separated by forward slashes.
> Separate path correctly for *sh on Windows

- autoload/ctrlp.vim
```
+root (with .git)
|
+-foo
|
+ bar.txt
+ baz.txt
```
1. start CtrlP on `foo`
2. open bar.txt
3. start CtrlP again
4. open baz.txt
We expect opening `bar.txt`. But actually open `foo/foo/baz.txt`.
> Fix abspath

- autoload/ctrlp.vim
When using the `CtrlPBuffers` command, the most recently used buffers would get push at the end of the suggestion list. This is annoying since when I switch buffers I, most of the time, want to go back to one of the latest buffers I worked on.  
I tried to used `CtrlpMRU` command instead but the list is much longer so the fuzzy search success rate is lower and often gets frustrated. 
Finally, the pull request re-introduce the feature as it was few months ago. I don't know if the current behaviour was intended?! 
Thanks!
> Fix most recent used buffer list sorting when using CtrlpBuffers after loading a Vim session.

- autoload/ctrlp.vim
Due to the terminal 'st' being left out of a list of hardcoded terminfo
names, the f5 key is not handled properly and will not refresh the
ctrlp window.
This extends the regex to match st, st-256color, st-meta, and
st-meta-256color.
In theory a better approach is to use the terminfo database, but this works for now.
Resolves #242
> Support f5 refresh in st terminal.

- autoload/ctrlp.vim
This allows correct switching to buffers with names like scp:// or term://
Fixes #231
> Fix switching to buffers with protocols

- autoload/ctrlp.vim
- Just checking for any buftype is insufficient
- See for example justinmk/vim-dirvish#43 -- a directory buffer should
have buftype=nofile, but ctrlp should still replace it
- Look instead for buftype=help or buftype=quickfix, explicitly
> Be more explicit about what windows to replace

- autoload/ctrlp.vim
Close #256 
@jonathanewerner @tacahiroy Could you please try this?
> use getcurpos/setpos instead of winsaveview/winrestview

- autoload/ctrlp.vim
- autoload/ctrlp/mrufiles.vim
- doc/ctrlp.txt
- plugin/ctrlp.vim
> Customizable core types

- autoload/ctrlp.vim
Related issue https://github.com/ctrlpvim/ctrlp.vim/issues/235
> Correct last focused window when PrtExit

- autoload/ctrlp.vim
- plugin/ctrlp.vim
When the user customized g:ctrlp_types to use a custom core mode set (possibly
with a custom relative order), the default mode (used when a bare :CtrlP is
issued) is wrong, along with the descriptive names of modes displayed in the
statusline. This pull request fixes these issues.
Fixes #309.
> Fix default mode and mode names when g:ctrlp_types is customized.

- plugin/ctrlp.vim
There's no point in tracking the files if the MRU plugin has been
explicitly disabled.
> Initialize the MRU plugin only when needed

- autoload/ctrlp.vim
CtrlP highlights only path and files as you type pattern.  Other
extensions, such as 'lines' or 'tags' do not have highlighting as you
type search pattern.  With this patch other other extensions also can
have pattern highlighting. For this, it is necessary to add:
let g:ctrlp_regex_always_higlight = 1
This patch works only when: g:ctrlp_regexp = 1. Which is quite safe as
universal approach.
Signed-off-by: Andrei Stepanov <astepano@redhat.com>
> Add g:ctrlp_regex_always_higlight option

- autoload/ctrlp.vim
- autoload/ctrlp/line.vim
With this patch:
- Typed pattern becomes search pattern in Vim.
- Cursors jumps directly to matched word. (Without this patch cursor
jumps only to matched line).
- User can press "n" or "N" to jump next/previous matched pattern.
While pressing "n" / "N" matched pattern got highlighted.
Signed-off-by: Andrei Stepanov <astepano@redhat.com>
> Update 'line' extension to act as Vim search pattern.

- autoload/ctrlp/line.vim
When navigating to a line and selecting it (without entering a search
string), vim would report "E35: No previous regular expression".
> Fix issue with CtrlPLine and empty search string

- autoload/ctrlp.vim
Hello, i often use terminal inside vim, but i use vim 8 instead of neovim, i'd like to see my terminals in buffer list and i think there's no reason to ignore vim8 terminals here.
> Add support for vim8 terminals

- autoload/ctrlp.vim
File types that is set by any CtrlP extensions should be respected.
Normally, the file type will be `ctrlp`, but it will be a combined file type like `ctrlp.vim`, `ctrlp.go` etc. if a CtrlP extension is set file types for CtrlP buffer.
> Fixes #450

- autoload/ctrlp.vim
The problem is:
1. filetype is 'ctrlp'
2. invoking an extension and it doesn't set filetype
3. then filetype is set to 'ctrlp.ctrlp'
The filetype should be just 'ctrlp' in this case.
> Fix filetype is set to multiple ctrlps

- autoload/ctrlp.vim
bufnr treats its argument as a regexp
if it starts with '^' and ends with '$'
> Fix #487 buffer name is not displayed problem 

- autoload/ctrlp.vim
* Issue:
Opening `ctrlp` in certain modes (`:CtrlPBufTag`, `:CtrlPLine`) seems to
trigger a partially deffective intialisation (for example, syntax
highlighting not working as expected).
* Changes:
`ctrlp#setlines()` has been split in two, as the second part (now in
`s:setlines_post()`) seems to need `&filetype`, and `s:DetectFileType()`
seems to need the first part of the old `ctrlp#setlines()` (now in
`s:setlines_pre()`).
> Split ctrlp#setlines() for ctrlp#init().  Fixes ctrlpvim/ctrlp.vim#463

- doc/ctrlp.txt
TIny change to fix what I believe to be a typo in the helpdocs.
> Fixes a typo in docs

- autoload/ctrlp.vim
Fix E94 on selecting a file when there is only one help window.
1. `vim -c 'help | only'`
1. `:CtrlPMRUFiles` or another CtrlP command
1. Select any file
1. E94 occurs
#444 has changed the behavior when the current buffer type is 'help' so that s:openfile() would always use 'b' command. This works well for `:CtrlPBufTag`, but doesn't work for other commands like `:CtrlPMRUFiles`.
```vim
let cmd =
\ md == 't' || s:splitwin == 1 ? ( useb ? 'tab sb' : 'tabe' ) :
\ md == 'h' || s:splitwin == 2 ? ( useb ? 'sb' : 'new' ) :
\ md == 'v' || s:splitwin == 3 ? ( useb ? 'vert sb' : 'vne' ) :
\ &bt == 'help' ? 'b' :
\ call('ctrlp#normcmd', useb ? ['b', 'bo vert sb'] : ['e'])
```
Use 'b' only if the current buffer type is 'help' and the opening file is the help file itself. Otherwise, use …
> Fix E94 on selecting a file when there is only one help window

- autoload/ctrlp.vim
I notice the arrow keys doesn't work when setting `tmux` to use _true color_, required for some color schemes.
This PR fix that by allowing the `:Tc` suffix in the term regex.
More info at:
- https://github.com/rakr/vim-one#tmux-support
- http://homeonrails.com/2016/05/truecolor-in-gnome-terminal-tmux-and-neovim/
My (g)vim version:
```
local/gvim 8.1.2102-1
Vi Improved, a highly configurable, improved version of the vi text editor (with advanced features, such as a GUI)
local/vim-runtime 8.1.2102-1
Vi Improved, a highly configurable, improved version of the vi text editor (shared runtime)
```
> Fix arrow keys when using true color config

- autoload/ctrlp.vim
- autoload/ctrlp/line.vim
This is a PR to solve the issue I mentioned at https://github.com/ctrlpvim/ctrlp.vim/issues/200. The idea comes from [quickpick.vim](https://github.com/prabirshrestha/quickpick.vim)
You can find a working example here. https://github.com/prabirshrestha/vim-lsp/pull/826
This requires changes to ctrlp. View demo at https://asciinema.org/a/333925.
Most of the heavy lifting is already done via lsp servers so it is very fast and responsive.
```vim
call ctrlp#set([{ 'label': 'hello' }])
```
> add async api support

- autoload/ctrlp.vim
- autoload/ctrlp/utils.vim
Optimized s:fnesc with avoiding check features.
Optimized s:usrign with making short-path of if/else/endif
Optimized with using get(dict, key, default)
> Optimize s:fnesc and s:usrign

- autoload/ctrlp.vim
> Restore line prefix

- autoload/ctrlp/buffertag.vim
> Print scoping information (e.g. classes) when using the buffertag extension

- autoload/ctrlp.vim
Fixes arrow keys, \<F5\>, and possibly others for the [Alacritty terminal](https://github.com/alacritty/alacritty).
Fixes #534 (when using Alacritty).
> Add alacritty to terminals with keycode fixes

- autoload/ctrlp.vim
This is revenge of https://github.com/ctrlpvim/ctrlp.vim/pull/594
> Lines can be omitted over s:maxlines

- doc/ctrlp.cnx
- doc/ctrlp.txt
`wildignore` to exclude file or dir only works with `GlobPath`, but not with the new `readdir`. It is iterated in https://github.com/ctrlpvim/ctrlp.vim/issues/598
I am updating the documentation regarding this and remove the `wildignore` options since `readdir` implementation is a preferred way. But I add another note to tell people they can still use `wildignore` if `g:ctrlp_use_readdir` is 0.
I have both english and chinese version of doc updated.
> Update doc related to wildignore

- autoload/ctrlp.vim
- doc/ctrlp.txt
Issue: https://github.com/ctrlpvim/ctrlp.vim/issues/600
I find that for large directory, CtrlP is not ranking results with the best candidate. This causes by a limit on the number of files it will sort. It will not sort the first readout if limit is set and director has more than limit number of files. This PR is to set `unlimit` sorting by default but users can custom the limit value to improve CtrlP performance on large directory.
> Improve CtrlP fuzzy finding results on large directories

- autoload/ctrlp.vim
https://github.com/ctrlpvim/ctrlp.vim/pull/597
So, CtrlP always be possible toomit lines if nolim is false. Now CtrlP get faster! YAY
> Omit lines for reader

- autoload/ctrlp/tag.vim
Note that in Neovim the 'cst' ('cscopetag') option has been removed.
> Ensure the 'cst' option is available before referencing it.
