autoload/ctrlp.vim
Hey, I added this option so that if there is only one match when CtrlP is opened, it jumps to that instead of opening the window. This is mostly useful together with CtrlP-Funky for me, but maybe others would like it.
=> added option g:open_single_match

doc/ctrlp.txt
Docs for these new options I added a few months ago. Remade pull request with new branch.
=> Documentation for ctrlp_line_prefix and ctrlp_open_single_match

readme.md
From https://github.com/kien/ctrlp.vim/issues/174#issuecomment-49747252
=> Added snippet showing how to ignore .gitignore files

autoload/ctrlp.vim, doc/ctrlp.txt
When this is set to 1, the <bs> on empty prompt exit CtrlP. #156
=> Implement brief_prompt mode

doc/ctrlp.txt
=> Update credits in helpfile.

autoload/ctrlp.vim
=> clear matches if the pattern is emtpy

autoload/ctrlp.vim
Because this commit change behavior of initial cursor location
=> Revert #186

autoload/ctrlp.vim
=> Customizable compare_lim

autoload/ctrlp.vim
=> Fix issue210

autoload/ctrlp.vim, doc/ctrlp.txt
Referring to #37. Fixes for issues #46 and #47 are included into this PR.
=> New buffer explorer mode with highlighting

autoload/ctrlp.vim
=> unload buffer if called PrtExit

autoload/ctrlp.vim
=> fix fuzzy filter

autoload/ctrlp.vim
Clsoe #272 
But I don't have plan to add default key assign.
=> add YankLine()

autoload/ctrlp.vim
=> try ctrlp_root_markers before looks up to root

autoload/ctrlp.vim
=> Possible to be specify g:ctrlp_user_command without %s

autoload/ctrlp.vim
=> Fix filetype detection mechanism

autoload/ctrlp.vim, doc/ctrlp.cnx, doc/ctrlp.txt
fix #369 and make it work with both VIm8 and Neovim
=> Re-Implement g:ctrlp_user_command_async

autoload/ctrlp.vim
Anyone could you please try this?
globpath
readdir
=> Improved performance

autoload/ctrlp.vim
=> Unescape paths for GlobPath

autoload/ctrlp/buffertag.vim
This PR fixes GitHub issue #583.
=> Fix broken buffertags

autoload/ctrlp.vim
=> Update highlight after ColorScheme event

autoload/ctrlp.vim
Calling ForceUpdate can be omitted for s:Close()
=> Close window fast

autoload/ctrlp.vim
=> fix not display cmdwin when `cmdheight = 0`
